# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets/dist"
  # Path to source folder
  src: "assets/src"
  # Paths to fonts
  fonts:
    - "vendor/bower-asset/font-awesome/web-fonts-with-css/webfonts/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "vendor/bower-asset/font-awesome/web-fonts-with-css/scss/fontawesome.scss"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    - "assets/src/js/functions.js"
